import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  header: {
    backgroundColor: "#4CAF50",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
  },
  greeting: { color: "#fff", fontSize: 18, fontWeight: "600" },
  avatar: { width: 40, height: 40, borderRadius: 20 },
  sectionCard: {
    backgroundColor: "#fff",
    margin: 16,
    borderRadius: 12,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 4,
  },
  sectionTitle: { fontSize: 16, fontWeight: "600", marginBottom: 12 },
  petRow: { flexDirection: "row", justifyContent: "space-around" },
  petCard: { alignItems: "center" },
  petImage: { width: 60, height: 60, borderRadius: 30 },
  petName: { marginTop: 6 },
  statusRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
  },
  statusCard: {
    backgroundColor: "#fff",
    flex: 1,
    margin: 6,
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 4,
    elevation: 2,
  },
  statusTitle: { fontSize: 14, fontWeight: "600", marginBottom: 8 },
  map: { width: 120, height: 100, borderRadius: 8, marginBottom: 8 },
  petStatusRow: { marginVertical: 4 },
  petStatusText: { fontWeight: "600" },
  healthText: { color: "green" },
  moodText: { color: "#e74c3c" },
  statusButton: {
    color: "#4CAF50",
    marginTop: 6,
    fontWeight: "500",
  },
  foodCard: {
    backgroundColor: "#f9f9f9",
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    borderRadius: 10,
    marginVertical: 6,
  },
  foodName: { fontWeight: "600", fontSize: 14 },
  foodDesc: { fontSize: 13, color: "#777" },
  vetCard: { flexDirection: "row" },
  vetImage: { width: 80, height: 80, borderRadius: 10 },
  vetInfo: { marginLeft: 10, flex: 1 },
  vetName: { fontWeight: "700" },
  vetDesc: { color: "#555" },
  vetRating: { color: "#f1c40f" },
  vetMeta: { fontSize: 12, color: "#777" },
  vetVisit: { fontSize: 12, color: "#888", marginVertical: 4 },
});
export default styles;
